### ISSUE TITLE
Technical unsoundness in the channel

### ISSUE THREAD

**Issue by noamtashma** [Rodrigodd/attractor-wallpaper#12]
Hey! Like I told you at reddit, your channel code should require `T: Send + Sync` instead of just `T: Sync`, since the channel enables sending the `T` between threads through a `&mut T`. This is essentially why `&mut T : Send` requires `T: Send + Sync`.

**Comment by Rodrigodd** [comment]
For the record, fixed by 4734997b8da2991f5f46968346835e1b126ea244.
